# PLACEHOLDER
applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  gloo-mp.gloo.deployment.image.repository:
    type: string
    default: gloo
  gloo-mp.gloo.deployment.image.registry:
    type: string
    default: gcr.io/solo-io-public/gloo/services/
  gloo-mp.gloo.deployment.image.tag:
    type: string
    default: 0.21.0
  gloo-mp.gloo.gloo.deployment.runAsUser:
    type: int
    default: 10101
  gloo-mp.gloo.discovery.deployment.runAsUser:
    type: int
    default: 10101
  gloo-mp.gloo.gateway.deployment.runAsUser:
    type: int
    default: 10101
  gloo-mp.gloo.gatewayProxies.podTemplate.runAsUser:
    type: int
    default: 10101
required:
- name
- namespace
