# PLACEHOLDER
applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  wordpressImage:
    type: string
    default: gcr.io/solo-io-public/gloo:0.21.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: wordpress.image.registry
            repo: wordpress.image.repository
            tag: wordpress.image.tag
required:
- name
- namespace
