# PLACEHOLDER v-mk-2
applicationApiVersion: v1beta1

properties:
  name:
    type: string
    default: gloo
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: gloo-system
    x-google-marketplace:
      type: NAMESPACE
  gloo.deployment.image.repository:
    type: string
    default: gloo
  gloo.deployment.image.registry:
    type: string
    default: gcr.io/solo-io-public/gloo/services/
  gloo.deployment.image.tag:
    type: string
    default: "1.0.0-rc2"
  gloo.gloo.deployment.runAsUser:
    type: int
    default: 10101
  gloo.discovery.deployment.runAsUser:
    type: int
    default: 10101
  gloo.gateway.deployment.runAsUser:
    type: int
    default: 10101
  gloo.gatewayProxies.podTemplate.runAsUser:
    type: int
    default: 10101
required:
- name
- namespace
