apiVersion: batch/v1
kind: Job
metadata:
  name: gloo-installer
  namespace: gloo-temp
spec:
  template:
    spec:
      serviceAccount: glooctl-installer
      containers:
      - name: glooctl-installer
        image: gcr.io/solo-io-public/gloo/installer:1.1c
        command: 
          - "sleep"
          - "6000"
          # - "glooctl"
          # - "install"
          # - "gateway"
          # # - "--dry-run"
          # - "--namespace"
          # - "gloo-temp"
          # - "--file"
          # - "/var/gloo/gloo-1.0.0.tgz"
      restartPolicy: Never
  backoffLimit: 4
